### ISSUE TITLE
Exception : Request has finished and HttpContext disposed.

### ISSUE THREAD

**Issue by malylemire1** [ElmahCore/ElmahCore#125]
Exception : Request has finished and HttpContext disposed.
Object name: 'HttpContext'.

Details : at Microsoft.AspNetCore.Http.DefaultHttpContext.ThrowContextDisposed()
at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Features()
at ElmahCore.Mvc.ElmahDiagnosticSqlObserver.OnNext(KeyValuePair`2 value)
at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
at System.Data.SqlClient.SqlClientDiagnosticListenerExtensions.WriteCommandAfter(DiagnosticListener this, Guid operationId, SqlCommand sqlCommand, String operation)
at System.Data.SqlClient.SqlCommand.<>c__DisplayClass130_0.b__2(Task`1 t)
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

**Comment by malylemire1** [comment]
The fix should be simple as that 

`ElmahLogFeature sqlLog;
try
{
	sqlLog = _provider.GetService<IHttpContextAccessor>()?.HttpContext?.Features.Get<ElmahLogFeature>();
	
}
catch (ObjectDisposedException)
{
	return;
}
if (sqlLog == null) return;`

**Comment by ElmahCore** [comment]
#125
