### ISSUE TITLE
SqlErrorLog throws SqlException  when message longer than 500 chars

### ISSUE THREAD

**Issue by tystol** [ElmahCore/ElmahCore#136]
We're seeing elmah errors not being logged in our prod system after upgrading to elmah core. Looking at the logs, we see the following logged:

```
System.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at ElmahCore.Sql.SqlErrorLog.Log(Guid id, Error error)
   at ElmahCore.Sql.SqlErrorLog.Log(Error error)
   at ElmahCore.ErrorLog.LogAsync(Error error, CancellationToken cancellationToken)
   at ElmahCore.Mvc.ErrorLogMiddleware.LogException(Exception e, HttpContext context, Func`3 onError, String body)
ClientConnectionId:9ce9cd5f-b83c-47b0-8666-5f95ee11dec7
Error Number:8152,State:30,Class:16
```

Looks like the new schema is limited to 500 chars, and it is pretty common to have exceptions with messages than longer than 500 chars.

**Comment by ElmahCore** [comment]
#136
