### ISSUE TITLE
Possible to disable connections to ip-api.com?

### ISSUE THREAD

**Issue by cvocvo** [ElmahCore/ElmahCore#171]
When I load ElmahCore, I'm seeing a console error due to our content security policy. Is it possible to disable this functionality in ElmahCore so that it doesn't try to connect to `ip-api.com`?

Thank you!

```
chunk-vendors.204a9d91.js:31  Refused to connect to 'http://ip-api.com/json/{IP Redacted}' because it violates the following Content Security Policy directive: "connect-src 'self' *.google-analytics.com".

(anonymous) @ chunk-vendors.204a9d91.js:31
e.exports @ chunk-vendors.204a9d91.js:31
e.exports @ chunk-vendors.204a9d91.js:19
Promise.then (async)
l.request @ chunk-vendors.204a9d91.js:1
a.forEach.l.<computed> @ chunk-vendors.204a9d91.js:1
(anonymous) @ chunk-vendors.204a9d91.js:1
item @ app.2c979763.js:1
na.run @ chunk-vendors.204a9d91.js:7
Kn @ chunk-vendors.204a9d91.js:7
(anonymous) @ chunk-vendors.204a9d91.js:7
ct @ chunk-vendors.204a9d91.js:7
Promise.then (async)
it @ chunk-vendors.204a9d91.js:7
ft @ chunk-vendors.204a9d91.js:7
ea @ chunk-vendors.204a9d91.js:7
na.update @ chunk-vendors.204a9d91.js:7
me.notify @ chunk-vendors.204a9d91.js:7
set @ chunk-vendors.204a9d91.js:7
aa.set @ chunk-vendors.204a9d91.js:7
onSelect @ app.2c979763.js:1
nt @ chunk-vendors.204a9d91.js:7
n @ chunk-vendors.204a9d91.js:7
Zr.i._wrapper @ chunk-vendors.204a9d91.js:7
app.2c979763.js:1 Error: Network Error
    at e.exports (chunk-vendors.204a9d91.js:17:12096)
    at h.onerror (chunk-vendors.204a9d91.js:31:187388)
```

**Comment by jafin** [comment]
https://github.com/ElmahCore/ElmahCore/issues/98
