### ISSUE TITLE
ElmahCore.Sql is not compliant with DBs with case-sensitive collation

### ISSUE THREAD

**Issue by yyordanov** [ElmahCore/ElmahCore#80]
The SQL statements in ElmahCore.Sql can only work on databases with case-insensitive collation. This effectively breaks the execution of Elmah SQL statements on such DBs. This has never been a problem in pre-.NET Core versions of Elamh and can be considered as a significant breaking change that forces to change the collation for the entire DB just just to be able to use Elmah! That is to me absolutely inappropriate and the fix is quite easy - just follow the casing of the DB objects as they are defined.

Examples wrong statements:

1. The DB objects/columns referenced in the following statements are defined with capital casing (information_schema.tables => INFORMATION_SCHEMA.TABLES)

```
SELECT 1 
WHERE EXISTS (
   SELECT 1
   FROM   **information_schema.tables** 
   WHERE  **table_schema** = 'dbo'
   AND    **table_name** = '**elmah_error**'
   )
```

2. The statememt for insertion of records is not consistent with the definition of the Elmah table itself!

`CREATE TABLE [dbo].[**ELMAH_Error**]
`
```
INSERT INTO **Elmah_Error** (ErrorId, Application, Host, Type, Source, Message, ""User"", StatusCode, TimeUtc, AllXml)
VALUES (@ErrorId, @Application, @Host, @Type, @Source, @Message, @User, @StatusCode, @TimeUtc, @AllXml)

```

Example error when running Elmah on a DB with case-sensitive collation (SQL_Latin1_General_CP1_CS_AS / SQL Server 2019 / version 15.0.2000.5):

System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'information_schema.tables'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at ElmahCore.Sql.SqlErrorLog.CreateTableIfNotExists()
   at ElmahCore.Sql.SqlErrorLog..ctor(String connectionString)
   at ElmahCore.Sql.SqlErrorLog..ctor(IOptions`1 option)

**Comment by yyordanov** [comment]
I just created a pull request for the fix. I will appreciate a lot if the fix is released soon since I'm currently finalizing the migration of a big product from .NET Framework to .NET 5 (ASP.NET Core) and this problem is quite blocking for me.

https://github.com/ElmahCore/ElmahCore/pull/81

**Comment by yyordanov** [comment]
Many thanks for the extremely quick release!!!
